<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
use Carbon\Carbon;


class QuestionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('quizzes')->insert([
    		[
    			'id' => '1',
    			'question' => 'Hey there! First, we need to know your legal name.',
    			'order' => '1' ,
    			'option' =>'',
    			'sub_question' => 'No',
    			'sub_heading'=> 'These are actual prescription medications, so we need to know your real information. No nicknames please!',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' => 'text',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'

    		],

    		[
    			'id' => '2',
    			'question' => 'What gender do you identify as?',
    			'order' =>'2',
    			'option' =>'Cisgender male (born and identify as a male)---Cisgender female (born and identify as a female)---Transgender---Gender Non-Binary---Other',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' => 'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],

    		[
    			'id' => '3',
    			'question' => 'What was your gender assigned at birth?',
    			'order' =>'3',
    			'option' =>'Male---Female',
    			'sub_question' =>'No',
    			'sub_heading'=>'Hormones can play a major role in skincare, and some treatments (like Accutane) involve different procedures depending on whether or not you’re able to get pregnant.',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],

    		[
    			'id' => '4',
    			'question' => 'Let’s learn a bit about your skin',
    			'order' =>'4',
    			'option' =>'',
    			'sub_question' =>'No',
    			'sub_heading'=>'Let’s keep it 💯. Getting clear, healthy skin isn’t about just one thing or what you put on your face – it’s about how prescriptions, diet, lifestyle, and regimens all play together.',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'0',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],

    		[
    			'id' => '5',
    			'question' => 'Where are you breaking out?',
    			'order' =>'5',
    			'option' =>'Face---Neck---Shoulders/Chest/Back',
    			'sub_question' =>'No',
    			'sub_heading'=>'Feel free to select more than one.',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'checkbox',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],

    		[
    			'id' => '6',
    			'question' => 'How would you best classify your skin type?',
    			'order' =>'6',
    			'option' =>'Very Dry---Dry---Combination---Oily---Very Oily',
    			'sub_question' =>'No',
    			'sub_heading'=>'This will give your dermatologist a good baseline to determine your plan, as treatment regimens can vary depending on your skin’s tendencies',
    			'status' =>'1',
    			'recommendation_product' =>'recommendation_7',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'yes'
    		],

    		[
    			'id' => '7',
    			'question' => 'What ethnicity(ethnicities) do you identify most with?',
    			'order' =>'7',
    			'option' =>'White/Caucasian---Hispanic---Black or African American---East Asian---South Asian---Middle Eastern---Native American---Pacific Islander---Other',
    			'sub_question' =>'No',
    			'sub_heading'=>'Feel free to select more than one.',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'checkbox',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '8',
    			'question' => 'How would you classify the severity of your acne?',
    			'order' =>'8',
    			'option' =>'just a few pimples here and there. Mostly whiteheads and blackheads with a few inflamed bumps here and there.---multiple inflamed pimples with new ones popping up. Acne is inflamed and red.---a large number of inflamed pimples with some deeper, more painful nodules that do not come to a head. Acne leaves moderate scarring.---a large number of inflamed pimples with multiple deep, painful nodules that do not come to a head. Acne leaves significant scarring.',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'recommendation_1',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '9',
    			'question' => 'Does your acne tend to scar, and if so how would you classify it?',
    			'order' =>'9',
    			'option' =>'My acne does not scar---I tend to get dark marks and pigmentation from my acne---My skin does tend to scar and causes depressions and bumps after my acne heals',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'recommendation_3',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'yes'
    		],
    		[
    			'id' => '10',
    			'question' => 'How long have you had your acne for?',
    			'order' =>'10',
    			'option' =>'<3 months---3-6 months---6 months-1 yr--->1 yr',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '11',
    			'question' => 'Does anyone in your immediate family have acne?',
    			'order' =>'11',
    			'option' =>'Yes---No',
    			'sub_question' =>'No',
    			'sub_heading'=>'Acne often runs in families and can be a good starting point to see what your acne may respond to.',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '12',
    			'question' => 'How much does your acne bother you?',
    			'order' =>'12',
    			'option' =>'It doesn’t really bother me---I do notice that it’s there, but it doesn’t prevent me from doing day to day things---It bothers me and I do feel self-conscious about it sometimes when other people point it out---It bothers me a lot.I sometimes skip out on things because of my acne and it affects my self-esteem.---My acne is the primary thing that holds back my confidence, and I feel like it holds me back from enjoying things as much as I want to.',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'recommendation_2',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'7',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '13',
    			'question' => 'How would you best describe your current diet?',
    			'order' =>'13',
    			'option' =>'Vegan/Vegetarian---Relatively Balanced Diet---Heavy on Processed Foods',
    			'sub_question' =>'No',
    			'sub_heading'=>'The science is in - diet can play a significant role in the health of your skin. Even with a great treatment plan, minimizing dairy intake and foods high in the Glycemic Index (GI) can help accelerate results in some cases.',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '14',
    			'question' => 'How would you rate your stress level on a scale of 1 to 10?',
    			'order' =>'14',
    			'option' =>'',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'number',
    			'min_number' =>'1',
    			'max_number' =>'10',
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '15',
    			'question' => 'Just a few questions about your medical history',
    			'order' =>'15',
    			'option' =>'',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '16',
    			'question' => 'Have you ever used any topical prescriptions for your acne before?',
    			'order' =>'16',
    			'option' =>'Yes---No',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'recommendation_4',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '17',
    			'question' => 'Have you ever used any oral medications for your acne before?',
    			'order' =>'17',
    			'option' =>'Yes---No',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'recommendation_6',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'yes'
    		],
    		[
    			'id' => '18',
    			'question' => 'Are you allergic to any medications that you’re aware of? If so, which?',
    			'order' =>'18',
    			'option' =>'Yes---No',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '19',
    			'question' => 'Please list any other medications that you’re currently taking.',
    			'order' =>'19',
    			'option' =>'',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'text',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '20',
    			'question' => 'What skincare products do you currently use in your routine? Please check all that apply.',
    			'order' =>'20',
    			'option' =>'Cleanser---Moisturizer---SPF---Toner---Other',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'checkbox',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '21',
    			'question' => 'Please provide some more detail on your skincare routine.',
    			'order' =>'21',
    			'option' =>'',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'7',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'text',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '22',
    			'question' => 'Would you like to include Tretinoin in your formula?',
    			'order' =>'1',
    			'option' =>'Yes---No',
    			'sub_question' =>'No',
    			'sub_heading'=>'Tretinoin is a topical form of Vitamin A that increases turnover of your skin, releasing clogged pores and trapped bacteria that may be causing acne. Tretinoin is a powerhouse acne-fighting ingredient, and we only recommend not adding it if you haven’t tolerated Tretinoin well in the past.',
    			'status' =>'1',
    			'recommendation_product' =>'recommendation_8',
    			'category_id'=>'9',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'yes'
    		],
    		[
    			'id' => '23',
    			'question' => 'Have you ever been treated for depression?',
    			'order' =>'1',
    			'option' =>'Yes---No',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'8',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '24',
    			'question' => 'Does anyone in your family have a history of depression?',
    			'order' =>'2',
    			'option' =>'Yes---No',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'8',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'radio',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '25',
    			'question' => 'What is your weight in lbs?',
    			'order' =>'3',
    			'option' =>'',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'8',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'text',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		[
    			'id' => '26',
    			'question' => 'What is your Height?',
    			'order' =>'4',
    			'option' =>'',
    			'sub_question' =>'No',
    			'sub_heading'=>'',
    			'status' =>'1',
    			'recommendation_product' =>'',
    			'category_id'=>'8',
    			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
    			'options_type' =>'text',
    			'min_number' =>NULL,
    			'max_number' =>NULL,
    			'use_for_recommendation' =>'no'
    		],
    		
    	]);
    }
}


